connector.name=zoho_books
endpoint=https://abhishekpalegar.app.n8n.cloud/webhook/zoho-books
# fallback-endpoint=https://abhishekpalegar.app.n8n.cloud/webhook-test/zoho-books
# n8n.schema-name=books
# n8n.table-name=items
# n8n.auth-token=your_token
# n8n.connect-timeout-ms=5000
# n8n.read-timeout-ms=30000
# n8n.page-size=1000
